Repository mgkid3310/AWESome, pull requests merged in 2019-06, with the labels that each got.

#46 Dev 1.1.8
  README.md
  addons/orbis_atc_environment/XEH_PREP.sqf
  addons/orbis_atc_environment/XEH_postInit.sqf
  addons/orbis_atc_environment/XEH_preInit.sqf
  addons/orbis_atc_environment/scripts/fnc_addATCConsole.sqf
  addons/orbis_atc_environment/scripts/fnc_addRadarScreen.sqf
  addons/orbis_atc_environment/scripts/fnc_atcRadarExit.sqf
  addons/orbis_atc_environment/scripts/fnc_atcRadarLoop.sqf
  addons/orbis_atc_environment/scripts/fnc_createMarkers.sqf
  addons/orbis_atc_environment/scripts/fnc_createTrails.sqf
  addons/orbis_atc_environment/scripts/fnc_getAutoTransponders.sqf
  addons/orbis_atc_environment/scripts/fnc_getInAddAction.sqf
  addons/orbis_atc_environment/scripts/fnc_updateATISdata.sqf
  addons/orbis_atc_environment/scripts/fnc_updateMarkerSpacing.sqf
  addons/orbis_awesome_main/XEH_postInit.sqf
  addons/orbis_cockpit/scripts/fnc_addACEInteractMenu.sqf
  addons/orbis_cockpit/scripts/fnc_getInAddAction.sqf
  addons/orbis_gpws/CfgVehicles.hpp
  addons/orbis_gpws/XEH_PREP.sqf
  addons/orbis_gpws/XEH_postInit.sqf
  addons/orbis_gpws/XEH_preInit.sqf
  addons/orbis_gpws/scripts/fnc_addACEInteractMenu.sqf
  addons/orbis_gpws/scripts/fnc_b747GPWS.sqf
  addons/orbis_gpws/scripts/fnc_b747GPWSinit.sqf
  addons/orbis_gpws/scripts/fnc_b747GPWStest.sqf
  addons/orbis_gpws/scripts/fnc_eachFrameHandler.sqf
  addons/orbis_gpws/scripts/fnc_f16ChaffFlare.sqf
  addons/orbis_gpws/scripts/fnc_f16GPWS.sqf
  addons/orbis_gpws/scripts/fnc_f16GPWSinit.sqf
  addons/orbis_gpws/scripts/fnc_f16GPWSterminate.sqf
  addons/orbis_gpws/scripts/fnc_f16GPWStest.sqf
  addons/orbis_gpws/scripts/fnc_getInAddAction.sqf
  addons/orbis_gpws/scripts/fnc_getInMan.sqf
  addons/orbis_gpws/scripts/fnc_incomingMSL.sqf
  addons/orbis_gpws/scripts/fnc_periodicCheck.sqf
  addons/orbis_gpws/scripts/fnc_playTestSound.sqf
  addons/orbis_gpws/scripts/fnc_ritaGPWS.sqf
  addons/orbis_gpws/scripts/fnc_ritaGPWSinit.sqf
  addons/orbis_gpws/scripts/fnc_ritaGPWStest.sqf
  addons/orbis_gpws/scripts/fnc_speakGPWS.sqf
  addons/orbis_gpws/scripts/fnc_startGPWS.sqf
  addons/orbis_gpws/scripts/fnc_terminateGPWS.sqf
  addons/orbis_ground/CfgVehicles.hpp
Labels: enhancement

#51 Added functionality for custom callsigns
  README.md
  addons/atc/XEH_PREP.hpp
  addons/atc/XEH_preInit.sqf
  addons/atc/functions/fnc_createMarkers.sqf
  addons/atc/functions/fnc_setCustomCallsign.sqf
Labels: enhancement

#54 Use ACE Units or CBA setting
  addons/cockpit/RscTitles.hpp
  addons/cockpit/XEH_PREP.hpp
  addons/cockpit/XEH_preInit.sqf
  addons/cockpit/functions/fnc_processSpeed.sqf
Labels: enhancement, in progress

#55 Missing bug fixes for checklists
  addons/cockpit/XEH_preInit.sqf
  addons/cockpit/functions/fnc_processSpeed.sqf
  addons/main/XEH_preInit.sqf
Labels: bug
